/**
 * 商业素材表
 */
PRAGMA foreign_keys = ON;
create table if not exists TB_MATERIAL_COMMERCIAL(
	ID INTEGER PRIMARY KEY NOT NULL,
	NAME TEXT,
	CAPTION TEXT,
	HOUR INTEGER,
	MINUTE INTEGER,
	SECOND INTEGER,
	STORE_ID INTEGER，
	FOREIGN KEY(STORE_ID) REFERENCES TB_COMMERCIAL_BUILDING(ID)
);

/**
 * 建材店
 */
insert into TB_MATERIAL_COMMERCIAL (ID, NAME, CAPTION, HOUR, MINUTE, SECOND, STORE_ID) values (1, 'Metal', '钉子', 0, 4, 0, 1);
insert into TB_MATERIAL_COMMERCIAL (ID, NAME, CAPTION, HOUR, MINUTE, SECOND, STORE_ID) values (2, 'Wood', '厚木板', 0, 24, 0, 1);
insert into TB_MATERIAL_COMMERCIAL (ID, NAME, CAPTION, HOUR, MINUTE, SECOND, STORE_ID) values (3, 'Plastic', '砖块', 0, 16, 0, 1);
insert into TB_MATERIAL_COMMERCIAL (ID, NAME, CAPTION, HOUR, MINUTE, SECOND, STORE_ID) values (4, 'Seed', '水泥', 0, 40, 0, 1);
insert into TB_MATERIAL_COMMERCIAL (ID, NAME, CAPTION, HOUR, MINUTE, SECOND, STORE_ID) values (5, 'Mineral', '胶水', 0, 48, 0, 1);
