/**
 * Specila items
 */
create table if not exists TB_SPECIAL_ITEMS(
	ID TEXT PRIMARY KEY NOT NULL,
	ITEM TEXT,
	DESCRIPTION TEXT,
	MAX_VALUE INTEGER,
	UNLOCKED_AT TEXT,
	IMG TEXT
);

INSERT INTO TB_SPECIAL_ITEMS ('ID', 'ITEM', 'DESCRIPTION', 'MAX_VALUE', 'UNLOCKED_AT', 'IMG') values ('S-vb', 'Vus Battery', 'Special Item to launch a Disaster.', 500, 'Population90000', 'http://vignette3.wikia.nocookie.net/simcity/images/9/92/S-vb.png/revision/latest/scale-to-width-down/25?cb=20150912031147&format=webp');
INSERT INTO TB_SPECIAL_ITEMS ('ID', 'ITEM', 'DESCRIPTION', 'MAX_VALUE', 'UNLOCKED_AT', 'IMG') values ('S-vg', 'Vus Gloves', 'Special Item to launch a Disaster.', 500, 'Population90000', 'http://vignette2.wikia.nocookie.net/simcity/images/d/de/S-vg.png/revision/latest/scale-to-width-down/25?cb=20150912031155&format=webp');
INSERT INTO TB_SPECIAL_ITEMS ('ID', 'ITEM', 'DESCRIPTION', 'MAX_VALUE', 'UNLOCKED_AT', 'IMG') values ('S-vr', 'Vus Remote', 'Special Item to launch a Disaster.', 500, 'Population90000', 'http://vignette4.wikia.nocookie.net/simcity/images/d/d1/S-vr.png/revision/latest/scale-to-width-down/25?cb=20150912031202&format=webp');
INSERT INTO TB_SPECIAL_ITEMS ('ID', 'ITEM', 'DESCRIPTION', 'MAX_VALUE', 'UNLOCKED_AT', 'IMG') values ('S-sc', 'Storage Camera', 'Special Item to upgrade the City Storage.', 650, 'Level1', 'http://vignette2.wikia.nocookie.net/simcity/images/2/27/S-sc.png/revision/latest/scale-to-width-down/25?cb=20150912031106&format=webp');
INSERT INTO TB_SPECIAL_ITEMS ('ID', 'ITEM', 'DESCRIPTION', 'MAX_VALUE', 'UNLOCKED_AT', 'IMG') values ('S-sl', 'Storage Lock', 'Special Item to upgrade the City Storage.', 650, 'Level1', 'http://vignette4.wikia.nocookie.net/simcity/images/8/8c/S-sl.png/revision/latest/scale-to-width-down/25?cb=20150912031116&format=webp');
INSERT INTO TB_SPECIAL_ITEMS ('ID', 'ITEM', 'DESCRIPTION', 'MAX_VALUE', 'UNLOCKED_AT', 'IMG') values ('S-sb', 'Storage Bars', 'Special Item to upgrade the City Storage.', 650, 'Level1', 'http://vignette3.wikia.nocookie.net/simcity/images/d/dd/S-sb.png/revision/latest/scale-to-width-down/25?cb=20150912031057&format=webp');
INSERT INTO TB_SPECIAL_ITEMS ('ID', 'ITEM', 'DESCRIPTION', 'MAX_VALUE', 'UNLOCKED_AT', 'IMG') values ('S-de', 'Dozer Exhaust', 'Special Item to open Expansion Areas.', 800, 'Level1', 'http://vignette1.wikia.nocookie.net/simcity/images/a/a8/S-de.png/revision/latest/scale-to-width-down/25?cb=20150912031006&format=webp');
INSERT INTO TB_SPECIAL_ITEMS ('ID', 'ITEM', 'DESCRIPTION', 'MAX_VALUE', 'UNLOCKED_AT', 'IMG') values ('S-dw', 'Dozer Wheel', 'Special Item to open Expansion Areas.', 800, 'Level1', 'http://vignette3.wikia.nocookie.net/simcity/images/b/ba/S-dw.png/revision/latest/scale-to-width-down/25?cb=20150912031016&format=webp');
INSERT INTO TB_SPECIAL_ITEMS ('ID', 'ITEM', 'DESCRIPTION', 'MAX_VALUE', 'UNLOCKED_AT', 'IMG') values ('S-db', 'Dozer Blade', 'Special Item to open Expansion Areas.', 800, 'Level1', 'http://vignette3.wikia.nocookie.net/simcity/images/1/1e/S-db.png/revision/latest/scale-to-width-down/25?cb=20150912030952&format=webp');
INSERT INTO TB_SPECIAL_ITEMS ('ID', 'ITEM', 'DESCRIPTION', 'MAX_VALUE', 'UNLOCKED_AT', 'IMG') values ('S-sw', 'Ships Wheel', 'Special Item to open Beach Areas.', 1500, 'Level15', 'http://vignette1.wikia.nocookie.net/simcity/images/6/63/S-sw.png/revision/latest/scale-to-width-down/25?cb=20150912031134&format=webp');
INSERT INTO TB_SPECIAL_ITEMS ('ID', 'ITEM', 'DESCRIPTION', 'MAX_VALUE', 'UNLOCKED_AT', 'IMG') values ('S-sm', 'Scuba Mask', 'Special Item to open Beach Areas.', 1500, 'Level15', 'http://vignette2.wikia.nocookie.net/simcity/images/0/07/S-sm.png/revision/latest/scale-to-width-down/25?cb=20150912031125&format=webp');
INSERT INTO TB_SPECIAL_ITEMS ('ID', 'ITEM', 'DESCRIPTION', 'MAX_VALUE', 'UNLOCKED_AT', 'IMG') values ('S-l', 'Lifebelt', 'Special Item to open Beach Areas.', 1500, 'Level15', 'http://vignette4.wikia.nocookie.net/simcity/images/3/3f/S-l.png/revision/latest/scale-to-width-down/25?cb=20150912031028&format=webp');
INSERT INTO TB_SPECIAL_ITEMS ('ID', 'ITEM', 'DESCRIPTION', 'MAX_VALUE', 'UNLOCKED_AT', 'IMG') values ('S-fc', 'Fashion Clothes', 'Special imported item to build and upgrade Parisian Zones.', 1800, 'Population140000', 'http://vignette1.wikia.nocookie.net/simcity/images/2/2a/S-fc.png/revision/latest/scale-to-width-down/25?cb=20151003190541&format=webp');
INSERT INTO TB_SPECIAL_ITEMS ('ID', 'ITEM', 'DESCRIPTION', 'MAX_VALUE', 'UNLOCKED_AT', 'IMG') values ('S-lab', 'La Baguette', 'Special imported item to build and upgrade Parisian Zones.', 1800, 'Population140000', 'http://vignette3.wikia.nocookie.net/simcity/images/2/2c/S-lab.png/revision/latest/scale-to-width-down/25?cb=20151003190602&format=webp');
INSERT INTO TB_SPECIAL_ITEMS ('ID', 'ITEM', 'DESCRIPTION', 'MAX_VALUE', 'UNLOCKED_AT', 'IMG') values ('S-lb', 'Luxury Bag', 'Special imported item to build and upgrade Parisian Zones.', 1800, 'Population140000', 'http://vignette2.wikia.nocookie.net/simcity/images/e/ee/S-lb.png/revision/latest/scale-to-width-down/25?cb=20151003190614&format=webp');
INSERT INTO TB_SPECIAL_ITEMS ('ID', 'ITEM', 'DESCRIPTION', 'MAX_VALUE', 'UNLOCKED_AT', 'IMG') values ('S-bt', 'Bonsai Tree', 'Special imported item to build and upgrade Tokyo Zones.', 2200, 'Population260000', 'http://vignette1.wikia.nocookie.net/simcity/images/f/f8/S-bt.png/revision/latest/scale-to-width-down/25?cb=20150912030940&format=webp');
INSERT INTO TB_SPECIAL_ITEMS ('ID', 'ITEM', 'DESCRIPTION', 'MAX_VALUE', 'UNLOCKED_AT', 'IMG') values ('S-lan', 'Lantern', 'Special imported item to build and upgrade Tokyo Zones.', 2200, 'Population260000', 'http://vignette1.wikia.nocookie.net/simcity/images/b/b3/S-lan.png/revision/latest/scale-to-width-down/25?cb=20150912031038&format=webp');
INSERT INTO TB_SPECIAL_ITEMS ('ID', 'ITEM', 'DESCRIPTION', 'MAX_VALUE', 'UNLOCKED_AT', 'IMG') values ('S-lc', 'Lucky Cat', 'Special imported item to build and upgrade Tokyo Zones.', 2200, 'Population260000', 'http://vignette3.wikia.nocookie.net/simcity/images/a/a5/S-lc.png/revision/latest/scale-to-width-down/25?cb=20150912031048&format=webp');
INSERT INTO TB_SPECIAL_ITEMS ('ID', 'ITEM', 'DESCRIPTION', 'MAX_VALUE', 'UNLOCKED_AT', 'IMG') values ('S-bhelmet', 'Bobbys Helmet', 'Special imported item to build and upgrade London Zones.', 2000, 'Population160000', 'http://vignette1.wikia.nocookie.net/simcity/images/f/f9/S-bhelmet.png/revision/latest/scale-to-width-down/25?cb=20151129200148&format=webp');
INSERT INTO TB_SPECIAL_ITEMS ('ID', 'ITEM', 'DESCRIPTION', 'MAX_VALUE', 'UNLOCKED_AT', 'IMG') values ('S-teapot', 'Teapot', 'Special imported item to build and upgrade London Zones.', 2000, 'Population160000', 'http://vignette2.wikia.nocookie.net/simcity/images/5/53/S-teapot.png/revision/latest/scale-to-width-down/25?cb=20151129200211&format=webp');
INSERT INTO TB_SPECIAL_ITEMS ('ID', 'ITEM', 'DESCRIPTION', 'MAX_VALUE', 'UNLOCKED_AT', 'IMG') values ('S-telbox', 'Telephone Box', 'Special imported item to build and upgrade London Zones.', 2000, 'Population160000', 'http://vignette4.wikia.nocookie.net/simcity/images/0/0e/S-telbox.png/revision/latest/scale-to-width-down/25?cb=20151129200229&format=webp');
